apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: sample-flask
spec:
  selector:
    app: sample-flask
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002